### ISSUE TITLE
Support for different dimensions

### ISSUE THREAD

**Issue by jplatte** [DorianRudolph/sirula#1]
… and maybe layouts?

First, it would be nice if I could make sirula not cover the bar at the top of my screen.

The way I'm using rofi currently is as a vertically and horizontally centered overlay, and I think if sirula would be able to do the same thing, I'd immediately switch to it, even without more layout tweaks (smaller entries would be nice, but the vastly better search results make it less important).

**Comment by DorianRudolph** [comment]
This should work now (aside from alternative layouts).

> First, it would be nice if I could make sirula not cover the bar at the top of my screen.

You can use the `margin_top` property to define the offset to the top.

> vertically and horizontally centered overlay

You can set all anchors to false, which will make the window centered
```
anchor_left = false
anchor_right = false
anchor_top = false
anchor_bottom = false
```
Set the window size with:
```
width = 600
height = 400
```
Some sizing is also possible using CSS but not maximum size as far as I know.

> smaller entries

You can configure `icon_size` in the config and set all other sizes (including font size) in CSS.

**Comment by jplatte** [comment]
Oh, the configuration section of the readme was so small I completely missed it! 😂

I will try it out tomorrow 🙂

**Comment by jplatte** [comment]
Works!
