### ISSUE TITLE
Customize search bar style

### ISSUE THREAD

**Issue by jplatte** [DorianRudolph/sirula#3]
I think the search bar would look better if it didn't have the usual text entry rounded corners. Maybe it should only have the blinking cursor and a border at the bottom, not any of the other edges. I'm not very accustomed to Gtk customization, so unsure how hard this would be.

**Comment by jplatte** [comment]
Oh, I see CSS is already supported. Maybe you should open up the GitHub wiki feature for this Repo so people have a place to share CSS tweaks :)

**Comment by DorianRudolph** [comment]
Yes, the following CSS should work.
```
#search {
    border: unset;
    outline: unset;
    box-shadow: unset;
    border-radius: unset;
    border-bottom: 1px solid white;
}
```

**Comment by jplatte** [comment]
Thanks! That style looks nice.

I think the Wiki can only be edited by you currently though.

**Comment by DorianRudolph** [comment]
It should be public now
