### ISSUE TITLE
Question about release tag for 1.0.1

### ISSUE THREAD

**Issue by h7x4** [DorianRudolph/sirula#38]
Hello!

We're about to update the version of this package in https://github.com/NixOS/nixpkgs/pull/281963, but we're a bit confused about the current version. There is a version bump to `1.0.1` in https://github.com/DorianRudolph/sirula/commit/70b5ce1936c819f4e5c8674e90145e5e7badcfa8, but no release tag. So we were wondering whether this is an official release or just bumping the version tag in preparation for next release?

**Comment by jlo62** [comment]
Hi, there's a new release, should have resolved itself.
