### ISSUE TITLE
launch apps in cgroups

### ISSUE THREAD

**Issue by jlo62** [DorianRudolph/sirula#42]
Hi, this would be a nice feature, as app detection in various task managers/system monitors rely on it to detect open windows, and their fallbacks are not reliable at all.

This would look like this:
```
systemd-run --scope --user --unit="app-[launcher-name]-[desktop-file-name]-[random-stuff]" [desktop-file-exec]
```
instead of just running the last part.

[launcher-name] would be sirula, [desktop-file-name] the .desktop file without the .desktop, and [random-stuff] is merely there to allow multiple instances of the app.\
gnome uses the pid of the app, while kde uses a full random uuid.

Here is a example for foot:
```
systemd-run --scope --user --unit="app-sirula-org.codeberg.dnkl.footclient-1234" footclient 
```

**Comment by qwertychouskie** [comment]
I don't think this was supposed to be closed yet.

**Comment by jlo62** [comment]
true :D I merged it into my fork's main, didn't think this would close it.
