### ISSUE TITLE
Multiple instances of sirula running

### ISSUE THREAD

**Issue by LuxLucian** [DorianRudolph/sirula#8]
Is there a way to make attempting to open a second instance of Sirula close the current one instead? This would make binding the command to a single hotkey more convenient.

**Comment by LuxLucian** [comment]
This bash script did solve the issue
ps -C sirula >/dev/null && pkill -9 sirula || sirula
Perhaps adding that to the main page might help some users?

**Comment by DorianRudolph** [comment]
That's a good idea. I think I will implement this directly in rust (using a "pidfile") once I have time.

**Comment by dafanasiev** [comment]
you don't need to use a pid-file, because GIO already support "singleton app" feature out of box (refer: https://developer.gnome.org/GtkApplication/  and https://developer.gnome.org/gio/stable/GApplication.html).

All what you need:

```rust
    application.connect_startup(|app| {
        load_css();
        activate(app);  //TODO: rename fn
    });
    
    application.connect_activate(|app| {
        //do nothing
    });
```
